name: Generate Snake Game

on:
  # Runs automatically every 24 hours
  schedule:
    - cron: "0 0 * * *" 
  # Allows you to run it manually whenever you want
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Generates the snake animation
      - uses: Platane/snk@v3
        with:
          # Your GitHub username
          github_user_name: Rohithgaloth
          outputs: |
            dist/pacman-contribution-graph.svg
            dist/pacman-contribution-graph-dark.svg?palette=github-dark

      # Pushes the result to a branch named "output"
      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
